# Generated by Django 2.2.1 on 2019-05-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitsandjuice', '0002_auto_20190509_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitsproduct',
            name='packaging',
            field=models.CharField(default='1', max_length=25, verbose_name='Упаковка'),
        ),
    ]
