# Generated by Django 2.2.1 on 2019-05-09 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fruitsandjuice', '0003_unitsproduct_packaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fruitsandjuice.UnitsProduct'),
            preserve_default=False,
        ),
    ]
