# Generated by Django 2.2.1 on 2019-05-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitsandjuice', '0005_product_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='anchor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Якорь для меню'),
        ),
    ]
